version: "3.8"
services:
  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_IMAGE_ID}:latest
    restart: always
    build: .
    ports:
      - "80:80"
    environment:
      IN_DOCKER: ${IN_DOCKER}
      BASE_HREF: ${BASE_HREF}
      AWS_REGION: ${AWS_REGION}
      DB_SECRET_NAME: ${DB_SECRET_NAME}